//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

public let R = Resource()

public struct Resource {
    public static var colorBundle: Foundation.Bundle = SFLibUI.bundle ?? .main
    public static var imageBundle: Foundation.Bundle = SFLibUI.bundle ?? .main
    
    public var color: color { .init(bundle: Self.colorBundle) }
    public var image: image { .init(bundle: Self.imageBundle) }
    
    
    /// This `_R.color` public struct is generated, and contains static references to 22 colors.
    public struct color {
        public let bundle: Foundation.Bundle
        
        /// Color `auxiliary`.
        public var auxiliary: RswiftResources.ColorResource { .init(name: "auxiliary", path: [], bundle: bundle) }
        
        /// Color `background`.
        public var background: RswiftResources.ColorResource { .init(name: "background", path: [], bundle: bundle) }
        
        /// Color `balckAlways`.
        public var balckAlways: RswiftResources.ColorResource { .init(name: "balckAlways", path: [], bundle: bundle) }
        
        /// Color `black`.
        public var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }
        
        /// Color `content`.
        public var content: RswiftResources.ColorResource { .init(name: "content", path: [], bundle: bundle) }
        
        /// Color `darkGray`.
        public var darkGray: RswiftResources.ColorResource { .init(name: "darkGray", path: [], bundle: bundle) }
        
        /// Color `detail`.
        public var detail: RswiftResources.ColorResource { .init(name: "detail", path: [], bundle: bundle) }
        
        /// Color `disabled`.
        public var disabled: RswiftResources.ColorResource { .init(name: "disabled", path: [], bundle: bundle) }
        
        /// Color `divider`.
        public var divider: RswiftResources.ColorResource { .init(name: "divider", path: [], bundle: bundle) }
        
        /// Color `error`.
        public var error: RswiftResources.ColorResource { .init(name: "error", path: [], bundle: bundle) }
        
        /// Color `gray`.
        public var gray: RswiftResources.ColorResource { .init(name: "gray", path: [], bundle: bundle) }
        
        /// Color `highlight`.
        public var highlight: RswiftResources.ColorResource { .init(name: "highlight", path: [], bundle: bundle) }
        
        /// Color `lightGray`.
        public var lightGray: RswiftResources.ColorResource { .init(name: "lightGray", path: [], bundle: bundle) }
        
        /// Color `link`.
        public var link: RswiftResources.ColorResource { .init(name: "link", path: [], bundle: bundle) }
        
        /// Color `placeholder`.
        public var placeholder: RswiftResources.ColorResource { .init(name: "placeholder", path: [], bundle: bundle) }
        
        /// Color `subtitle`.
        public var subtitle: RswiftResources.ColorResource { .init(name: "subtitle", path: [], bundle: bundle) }
        
        /// Color `success`.
        public var success: RswiftResources.ColorResource { .init(name: "success", path: [], bundle: bundle) }
        
        /// Color `theme`.
        public var theme: RswiftResources.ColorResource { .init(name: "theme", path: [], bundle: bundle) }
        
        /// Color `title`.
        public var title: RswiftResources.ColorResource { .init(name: "title", path: [], bundle: bundle) }
        
        /// Color `warning`.
        public var warning: RswiftResources.ColorResource { .init(name: "warning", path: [], bundle: bundle) }
        
        /// Color `white`.
        public var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
        
        /// Color `whiteAlways`.
        public var whiteAlways: RswiftResources.ColorResource { .init(name: "whiteAlways", path: [], bundle: bundle) }
    }
    
    /// This `_R.image` public struct is generated, and contains static references to 2 images, and 4 namespaces.
    public struct image {
        public let bundle: Foundation.Bundle
        
        /// Image `back`.
        public var back: RswiftResources.ImageResource { .init(name: "back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        
        /// Image `close`.
        public var close: RswiftResources.ImageResource { .init(name: "close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        public var arrow: arrow { .init(bundle: bundle) }
        public var doc: doc { .init(bundle: bundle) }
        public var hud: hud { .init(bundle: bundle) }
        public var triangle: triangle { .init(bundle: bundle) }
        
        public func arrow(bundle: Foundation.Bundle) -> arrow {
            .init(bundle: bundle)
        }
        public func doc(bundle: Foundation.Bundle) -> doc {
            .init(bundle: bundle)
        }
        public func hud(bundle: Foundation.Bundle) -> hud {
            .init(bundle: bundle)
        }
        public func triangle(bundle: Foundation.Bundle) -> triangle {
            .init(bundle: bundle)
        }
        
        
        /// This `_R.image.arrow` public struct is generated, and contains static references to 4 arrows.
        public struct arrow {
            public let bundle: Foundation.Bundle
            
            /// Image `arrow/bottom`.
            public var bottom: RswiftResources.ImageResource { .init(name: "arrow/bottom", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `arrow/left`.
            public var left: RswiftResources.ImageResource { .init(name: "arrow/left", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `arrow/right`.
            public var right: RswiftResources.ImageResource { .init(name: "arrow/right", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `arrow/top`.
            public var top: RswiftResources.ImageResource { .init(name: "arrow/top", path: ["arrow"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
        
        /// This `_R.image.doc` public struct is generated, and contains static references to 2 docs.
        public struct doc {
            public let bundle: Foundation.Bundle
            
            /// Image `doc/file`.
            public var file: RswiftResources.ImageResource { .init(name: "doc/file", path: ["doc"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `doc/folder`.
            public var folder: RswiftResources.ImageResource { .init(name: "doc/folder", path: ["doc"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
        
        /// This `_R.image.hud` public struct is generated, and contains static references to 6 huds.
        public struct hud {
            public let bundle: Foundation.Bundle
            
            /// Image `hud/error`.
            public var error: RswiftResources.ImageResource { .init(name: "hud/error", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `hud/failure`.
            public var failure: RswiftResources.ImageResource { .init(name: "hud/failure", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `hud/info`.
            public var info: RswiftResources.ImageResource { .init(name: "hud/info", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `hud/loading`.
            public var loading: RswiftResources.ImageResource { .init(name: "hud/loading", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `hud/success`.
            public var success: RswiftResources.ImageResource { .init(name: "hud/success", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `hud/warning`.
            public var warning: RswiftResources.ImageResource { .init(name: "hud/warning", path: ["hud"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
        
        /// This `_R.image.triangle` public struct is generated, and contains static references to 4 triangles.
        public struct triangle {
            public let bundle: Foundation.Bundle
            
            /// Image `triangle/bottom`.
            public var bottom: RswiftResources.ImageResource { .init(name: "triangle/bottom", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `triangle/left`.
            public var left: RswiftResources.ImageResource { .init(name: "triangle/left", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `triangle/right`.
            public var right: RswiftResources.ImageResource { .init(name: "triangle/right", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `triangle/top`.
            public var top: RswiftResources.ImageResource { .init(name: "triangle/top", path: ["triangle"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
    }
    
}
